//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.Status
{ 

public sealed partial class StatusTable
{
    private readonly Dictionary<int, Status.StatusConfig> _dataMap;
    private readonly List<Status.StatusConfig> _dataList;
    
    public StatusTable(JSONNode _json)
    {
        _dataMap = new Dictionary<int, Status.StatusConfig>();
        _dataList = new List<Status.StatusConfig>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = Status.StatusConfig.DeserializeStatusConfig(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, Status.StatusConfig> DataMap => _dataMap;
    public List<Status.StatusConfig> DataList => _dataList;

    public Status.StatusConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Status.StatusConfig Get(int key) => _dataMap[key];
    public Status.StatusConfig this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}