//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using SimpleJSON;


namespace cfg
{ 
   
public sealed partial class Tables
{
    public Skill.SkillTable SkillTable {get; }
    public Effect.EffectTable EffectTable {get; }
    public Condition.ConditionTable ConditionTable {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        SkillTable = new Skill.SkillTable(loader("skill_skilltable")); 
        tables.Add("Skill.SkillTable", SkillTable);
        EffectTable = new Effect.EffectTable(loader("effect_effecttable")); 
        tables.Add("Effect.EffectTable", EffectTable);
        ConditionTable = new Condition.ConditionTable(loader("condition_conditiontable")); 
        tables.Add("Condition.ConditionTable", ConditionTable);
        PostInit();

        SkillTable.Resolve(tables); 
        EffectTable.Resolve(tables); 
        ConditionTable.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        SkillTable.TranslateText(translator); 
        EffectTable.TranslateText(translator); 
        ConditionTable.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}