//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using SimpleJSON;


namespace cfg
{ 
   
public sealed partial class Tables
{
    public Skill.SkillTable SkillTable {get; }
    public Skill.SkillEffectTable SkillEffectTable {get; }
    public Status.StatusTable StatusTable {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        SkillTable = new Skill.SkillTable(loader("skill_skilltable")); 
        tables.Add("Skill.SkillTable", SkillTable);
        SkillEffectTable = new Skill.SkillEffectTable(loader("skill_skilleffecttable")); 
        tables.Add("Skill.SkillEffectTable", SkillEffectTable);
        StatusTable = new Status.StatusTable(loader("status_statustable")); 
        tables.Add("Status.StatusTable", StatusTable);
        PostInit();

        SkillTable.Resolve(tables); 
        SkillEffectTable.Resolve(tables); 
        StatusTable.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        SkillTable.TranslateText(translator); 
        SkillEffectTable.TranslateText(translator); 
        StatusTable.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}