//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.Skill.Enum
{ 
    /// <summary>
    /// 行为控制
    /// </summary>
    [System.Flags]
    public enum ActionControlType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 禁止移动
        /// </summary>
        MoveForbid = 1,
        /// <summary>
        /// 禁止施法
        /// </summary>
        SkillForbid = 2,
        /// <summary>
        /// 禁止普攻
        /// </summary>
        AttackForbid = 4,
    }

} 
