//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.Skill.Enum
{ 
    /// <summary>
    /// 属性类型
    /// </summary>
    public enum AttributeType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 最大生命值
        /// </summary>
        HealthPointMax = 1,
        /// <summary>
        /// 生命值
        /// </summary>
        HealthPoint = 2,
        /// <summary>
        /// 攻击力
        /// </summary>
        Attack = 3,
        /// <summary>
        /// 护甲
        /// </summary>
        Defense = 4,
        /// <summary>
        /// 法术强度
        /// </summary>
        AbilityPower = 5,
        /// <summary>
        /// 魔法抗性
        /// </summary>
        SpellResistance = 6,
        /// <summary>
        /// 暴击率
        /// </summary>
        CriticalProbability = 7,
        /// <summary>
        /// 移动速度
        /// </summary>
        MoveSpeed = 8,
        /// <summary>
        /// 造成伤害
        /// </summary>
        CauseDamage = 9,
    }

} 
