//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.Skill.Enum
{ 
    /// <summary>
    /// 技能效果类型
    /// </summary>
    public enum EffectType
    {
        /// <summary>
        /// 伤害
        /// </summary>
        Damage = 0,
        /// <summary>
        /// 治疗
        /// </summary>
        Cure = 1,
    }

} 
