//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.Skill.Enum
{ 
    /// <summary>
    /// 修饰类型
    /// </summary>
    public enum ModifyType
    {
        /// <summary>
        /// 固定
        /// </summary>
        Add = 0,
        /// <summary>
        /// 百分比
        /// </summary>
        PctAdd = 1,
    }

} 
