//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.Skill.Enum
{ 
    /// <summary>
    /// 目标类型
    /// </summary>
    public enum SkillAffectTargetType
    {
        /// <summary>
        /// 自身
        /// </summary>
        Self = 0,
        /// <summary>
        /// 友方
        /// </summary>
        SelfTeam = 1,
        /// <summary>
        /// 敌方
        /// </summary>
        EnemyTeam = 2,
    }

} 
