//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.Skill.Enum
{ 
    /// <summary>
    /// 目标选择方式
    /// </summary>
    public enum SkillTargetSelectType
    {
        /// <summary>
        /// 手动指定
        /// </summary>
        PlayerSelect = 0,
        /// <summary>
        /// 碰撞检测
        /// </summary>
        CollisionSelect = 1,
        /// <summary>
        /// 条件检测
        /// </summary>
        ConditionSelect = 2,
        /// <summary>
        /// 自定义
        /// </summary>
        Custom = 3,
    }

} 
