//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.Effect.Enum
{ 
    /// <summary>
    /// 控制类型
    /// </summary>
    [System.Flags]
    public enum ControlType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 禁止攻击
        /// </summary>
        AttackForbid = 1,
        /// <summary>
        /// 禁止移动
        /// </summary>
        MoveForbid = 2,
        /// <summary>
        /// 禁止施法
        /// </summary>
        SpellForbid = 3,
    }

} 
