//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.Effect.Enum
{ 
    /// <summary>
    /// 伤害类型
    /// </summary>
    public enum DamageType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 物理
        /// </summary>
        Physics = 1,
        /// <summary>
        /// 魔法
        /// </summary>
        Magic = 2,
        /// <summary>
        /// 真实
        /// </summary>
        Real = 3,
    }

} 
