//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.Effect.Enum
{ 
    /// <summary>
    /// 效果目标
    /// </summary>
    public enum EffectTarget
    {
        /// <summary>
        /// 自身
        /// </summary>
        Self = 0,
        /// <summary>
        /// 目标
        /// </summary>
        Target = 1,
    }

} 
