//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.Effect.Enum
{ 
    /// <summary>
    /// 生效时机
    /// </summary>
    public enum EffectTiming
    {
        /// <summary>
        /// 立刻
        /// </summary>
        Immediate = 0,
        /// <summary>
        /// 持续时间
        /// </summary>
        Duration = 1,
        /// <summary>
        /// 间隔触发
        /// </summary>
        Interval = 2,
    }

} 
