//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.Condition.Enum
{ 
    /// <summary>
    /// 选择区域的范围类型
    /// </summary>
    public enum AreaType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 矩形
        /// </summary>
        Rect = 1,
        /// <summary>
        /// 圆形
        /// </summary>
        Round = 2,
        /// <summary>
        /// 扇形
        /// </summary>
        Sector = 3,
    }

} 
