//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.Condition.Enum
{ 
    /// <summary>
    /// 检测规则
    /// </summary>
    public enum RuleType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 手动指定
        /// </summary>
        Select = 1,
        /// <summary>
        /// 范围检测
        /// </summary>
        Area = 2,
        /// <summary>
        /// 自定义
        /// </summary>
        Custom = 3,
    }

} 
