//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.Condition.Enum
{ 
    /// <summary>
    /// 目标类型
    /// </summary>
    public enum TargetType
    {
        /// <summary>
        /// 友方
        /// </summary>
        Team = 0,
        /// <summary>
        /// 敌方
        /// </summary>
        Enemy = 1,
    }

} 
