//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.Effect
{ 

public sealed partial class EffectTable
{
    private readonly Dictionary<int, Effect.EffectConfig> _dataMap;
    private readonly List<Effect.EffectConfig> _dataList;
    
    public EffectTable(JSONNode _json)
    {
        _dataMap = new Dictionary<int, Effect.EffectConfig>();
        _dataList = new List<Effect.EffectConfig>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = Effect.EffectConfig.DeserializeEffectConfig(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, Effect.EffectConfig> DataMap => _dataMap;
    public List<Effect.EffectConfig> DataList => _dataList;

    public Effect.EffectConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Effect.EffectConfig Get(int key) => _dataMap[key];
    public Effect.EffectConfig this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}