//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.Skill
{ 

public sealed partial class SkillEffectTable
{
    private readonly Dictionary<int, Skill.SkillEffectConfig> _dataMap;
    private readonly List<Skill.SkillEffectConfig> _dataList;
    
    public SkillEffectTable(JSONNode _json)
    {
        _dataMap = new Dictionary<int, Skill.SkillEffectConfig>();
        _dataList = new List<Skill.SkillEffectConfig>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = Skill.SkillEffectConfig.DeserializeSkillEffectConfig(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, Skill.SkillEffectConfig> DataMap => _dataMap;
    public List<Skill.SkillEffectConfig> DataList => _dataList;

    public Skill.SkillEffectConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Skill.SkillEffectConfig Get(int key) => _dataMap[key];
    public Skill.SkillEffectConfig this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}