//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.Condition
{ 

public sealed partial class ConditionConfig :  Bright.Config.BeanBase 
{
    public ConditionConfig(JSONNode _json) 
    {
        { if(!_json["Id"].IsNumber) { throw new SerializationException(); }  Id = _json["Id"]; }
        { if(!_json["TargetType"].IsNumber) { throw new SerializationException(); }  TargetType = (Condition.Enum.TargetType)_json["TargetType"].AsInt; }
        { if(!_json["RuleType"].IsNumber) { throw new SerializationException(); }  RuleType = (Condition.Enum.RuleType)_json["RuleType"].AsInt; }
        { if(!_json["AreaType"].IsNumber) { throw new SerializationException(); }  AreaType = (Condition.Enum.AreaType)_json["AreaType"].AsInt; }
        { if(!_json["CustomRule"].IsNumber) { throw new SerializationException(); }  CustomRule = _json["CustomRule"]; }
        { var _json2 = _json["AreaInfo"]; if(!_json2.IsObject) { throw new SerializationException(); }  float __x; { if(!_json2["x"].IsNumber) { throw new SerializationException(); }  __x = _json2["x"]; } float __y; { if(!_json2["y"].IsNumber) { throw new SerializationException(); }  __y = _json2["y"]; } AreaInfo = new UnityEngine.Vector2(__x, __y); }
        PostInit();
    }

    public ConditionConfig(int Id, Condition.Enum.TargetType TargetType, Condition.Enum.RuleType RuleType, Condition.Enum.AreaType AreaType, int CustomRule, UnityEngine.Vector2 AreaInfo ) 
    {
        this.Id = Id;
        this.TargetType = TargetType;
        this.RuleType = RuleType;
        this.AreaType = AreaType;
        this.CustomRule = CustomRule;
        this.AreaInfo = AreaInfo;
        PostInit();
    }

    public static ConditionConfig DeserializeConditionConfig(JSONNode _json)
    {
        return new Condition.ConditionConfig(_json);
    }

    public int Id { get; private set; }
    /// <summary>
    /// 目标类型
    /// </summary>
    public Condition.Enum.TargetType TargetType { get; private set; }
    /// <summary>
    /// 检测规则
    /// </summary>
    public Condition.Enum.RuleType RuleType { get; private set; }
    /// <summary>
    /// 范围类型
    /// </summary>
    public Condition.Enum.AreaType AreaType { get; private set; }
    /// <summary>
    /// 自定义规则ID
    /// </summary>
    public int CustomRule { get; private set; }
    /// <summary>
    /// 范围信息
    /// </summary>
    public UnityEngine.Vector2 AreaInfo { get; private set; }

    public const int __ID__ = -186046166;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "TargetType:" + TargetType + ","
        + "RuleType:" + RuleType + ","
        + "AreaType:" + AreaType + ","
        + "CustomRule:" + CustomRule + ","
        + "AreaInfo:" + AreaInfo + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
