//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.Status.Enum
{ 
    /// <summary>
    /// 属性类型
    /// </summary>
    public enum StatusPropertyType
    {
        /// <summary>
        /// 攻击
        /// </summary>
        Attack = 0,
        /// <summary>
        /// 基础生命
        /// </summary>
        Health = 1,
        /// <summary>
        /// 最大生命
        /// </summary>
        HealthMax = 2,
    }

} 
