//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.Status.Enum
{ 
    /// <summary>
    /// 状态类型
    /// </summary>
    public enum StatusType
    {
        /// <summary>
        /// 属性修饰
        /// </summary>
        PropertyModify = 0,
        /// <summary>
        /// 行为禁止
        /// </summary>
        ActionForbid = 1,
        /// <summary>
        /// 伤害
        /// </summary>
        Damage = 2,
        /// <summary>
        /// 治疗
        /// </summary>
        Cure = 3,
    }

} 
