//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.Status.Enum
{ 
    /// <summary>
    /// 控制类型
    /// </summary>
    [System.Flags]
    public enum StatusControlType
    {
        /// <summary>
        /// 攻击
        /// </summary>
        AttackForbid = 1,
        /// <summary>
        /// 技能
        /// </summary>
        SkillForbid = 2,
        /// <summary>
        /// 移动
        /// </summary>
        MoveForbid = 4,
    }

} 
